ignore:
   - "Pods"
   - "Tests"
   - "Example"
coverage:
   range: 70..100
   round: down
   precision: 2
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto