ignore:
   - "Pods"
   - "Tests"
   - "Example"
coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto 
        if_ci_failed: error
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error