ignore:
   - "Pods"
   - "Tests"
   - "Example"
   - "Carthage"
   - "MiniAppCarthage"
   - "Sources/Classes/ui"
   - "Sources/Classes/core/Display/MiniAppExternalWebViewController.swift"
   - "Sources/Classes/core/Display/MiniAppNavigationConfig.swift"
   - "Sources/Classes/core/Extensions/RealMiniAppView+WKUIDelegate.swift"
   - "Sources/Classes/admob/AdMobDisplayer.swift"
   - "Sources/Classes/core/Display/ViewControllers/Custom\ Permissions/CustomPermissionsRequestViewController.swift"

coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto 
        if_ci_failed: error
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error
