disabled_rules: # rule identifiers to exclude from running
  - nesting
# parameterized rules are first parameterized as a warning level, then error level.
line_length:
  - 200 # warning
  - 300 # error
function_body_length:
  max_length:
    warning: 30
    error: 50
type_body_length:
  - 300
  - 400
cyclomatic_complexity:
  - 20
  - 20
# paths to ignore
identifier_name:
  excluded:
    - id
excluded:
  - Pods
  - vendor
