language: swift
xcode_workspace: MiniApp.xcworkspace
xcode_scheme: Tests
osx_image: xcode11.2

before_install:
- bundle install
- gem update fastlane cocoapods --no-document
- pod repo update

script:
- fastlane ci