language: swift
xcode_workspace: MiniApp.xcworkspace
xcode_scheme: Tests
osx_image: xcode11.2

before_install:
- bundle install
- gem update fastlane cocoapods --no-document
- pod repo update

script:
- fastlane ci
- bundle exec danger

after_success:
  # generate docs
- jazzy --xcodebuild-arguments -scheme,Tests --module MiniApp --source-directory MiniApp --podspec MiniApp.podspec --readme README.md