language: swift
xcode_workspace: MiniApp.xcworkspace
xcode_scheme: Tests
osx_image: xcode11.2

before_install:
- pod repo update

script:
- fastlane ci
- bundle exec danger

after_success:
- jazzy
  --xcodebuild-arguments -scheme,Tests
  --module MiniApp
  --source-directory MiniApp
  --podspec MiniApp.podspec
  --readme README.md

deploy:
  provider: script
  skip_cleanup: true
  script: |
    pod spec lint --allow-warnings 
    && pod trunk push --allow-warnings --verbose
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v

notifications:
  slack:
    rooms:
      secure: $SLACK_TOKEN
