const REQUEST_HOST_ENVIRONMENT_INFO_SUCCESS =
  'REQUEST_HOST_ENVIRONMENT_INFO_SUCCESS';
const REQUEST_HOST_ENVIRONMENT_INFO_ERROR =
  'REQUEST_HOST_ENVIRONMENT_INFO_ERROR';

export {
  REQUEST_HOST_ENVIRONMENT_INFO_SUCCESS,
  REQUEST_HOST_ENVIRONMENT_INFO_ERROR,
};
