// flow-typed signature: 47fd1add534dde8e5435d07e3cb8ec91
// flow-typed version: <<STUB>>/js-miniapp-sdk_v0.1.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-miniapp-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-miniapp-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-miniapp-sdk/build/bundle' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/src' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/src/miniapp' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/test/miniapp.spec' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/prettier.config' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-miniapp-sdk/build/bundle.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/bundle'>;
}
declare module 'js-miniapp-sdk/build/src/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/src'>;
}
declare module 'js-miniapp-sdk/build/src/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/src'>;
}
declare module 'js-miniapp-sdk/build/src/miniapp.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/src/miniapp'>;
}
declare module 'js-miniapp-sdk/build/test/miniapp.spec.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/test/miniapp.spec'>;
}
declare module 'js-miniapp-sdk/prettier.config.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/prettier.config'>;
}
declare module 'js-miniapp-sdk/test/setup.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/test/setup'>;
}
