name: Build Documentation 

on:
  pull_request:
    branches: [ master, candidate, gh-pages ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build Documentation
      run: |
        $GITHUB_WORKSPACE/scripts/build-doc.sh